### ISSUE TITLE
Configuration File Format

### ISSUE THREAD

**Issue by Michael21107** [SteveOhByte/Armoury#2]
I would strongly suggest changing the .lc files to .ini (or .xml if needed) as .lc files don't open in any program by default (people have to manually select a text editor and therefore know it is a text file for settings editing) and it's not widely used so people may be confused on where is the .ini (i saw lc files for the first time in _armoury_ afaik)

**Comment by SteveOhByte** [comment]
I understand the suggestion, but I'll be keeping [LiteConfig](https://github.com/SteveOhByte/LiteConfig) as the file type for this plugin. I built **LC** myself because I was tired of how I kept stumbling over myself while trying to use formats such as **INI**, **JSON**, or **TOML**. In particular, I didn't (and don't) like how restrictive they are to both the developer and end user in readability.

While **LC** is a very simple little library, I like using it as the developer, and at the end of the day I made this plugin for myself first, and opened it secondarily.

All that said, I have, in the most recent version, added a system to offer the user an opportunity to associate .lc with notepad, if they did not read the readme.txt file included with the mod download. 
This version has yet to be pushed, as it will contain other small improvements to the mod.

**Comment by Michael21107** [comment]
i was able to open the lc files in both Notepad++ and standard Notepad, can you make .lc files somehow get opened by notepad or can only Microsoft do that?

**Comment by SteveOhByte** [comment]
Yes, it requires a registry edit however, and so RagePluginHook would need to be run with admin rights.

In release version 1.0.7 there will be a button on-screen when you load the game, asking if you want to set Notepad to open .lc files if you haven't already.

In the readme, there is also a note telling users to open it with any text editor.

**Comment by Michael21107** [comment]
gotcha, thanks
